version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    depends_on:
      - mongo
    networks:
      - mern-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5073:80"
    depends_on:
      - backend
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
